export const TEST = 'Test'
export const BASE_URL = 'http://transportapi.com/v3/uk'
export const FETCH_NEARBY_BUS_STOPS = 'FETCH_NEARBY_BUS_STOPS'
export const FETCH_NEARBY_BUS_STOPS_SUCCESS = 'FETCH_NEARBY_BUS_STOPS_SUCCESS'
export const FETCH_NEARBY_BUS_STOPS_FAIL = 'FETCH_NEARBY_BUS_STOPS_FAIL'

export const FETCH_DEPARTURES = 'FETCH_DEPARTURES'
export const FETCH_DEPARTURES_SUCCESS = 'FETCH_DEPARTURES_SUCCESS'
export const FETCH_DEPARTURES_FAIL = 'FETCH_DEPARTURES_FAIL'
export const SET_DEPARTURES = 'SET_DEPARTURES'

export const FETCH_DIRECTIONS = 'FETCH_DIRECTIONS'
export const FETCH_DIRECTIONS_SUCCESS = 'FETCH_DIRECTIONS_SUCCESS'
export const FETCH_DIRECTIONS_FAIL = 'FETCH_DEPARTURES_FAIL'
